- id: clj-kondo
  name: clj-kondo
  description: Run lint rules with clj-kondo
  types: [clojure]
  entry: hooks/clj-kondo-pre-commit
  language: script
  require_serial: true
  args: ["warning"]
- id: zprint
  name: format with zprint
  description: Format files using zprint
  types: [clojure]
  entry: hooks/zprint-pre-commit
  language: script
  require_serial: false
- id: kaocha
  name: run tests
  description: Run kaocha tests
  types: [clojure]
  entry: hooks/kaocha-pre-commit
  language: script
  pass_filenames: false
  require_serial: false
- id: cljstyle
  name: run cljstyle
  description: Format files using cljstyle
  types: [clojure]
  entry: hooks/cljstyle-pre-commit
  language: script
  pass_filenames: false
  require_serial: false
  args: ["check"]