#!/usr/bin/env bash

if ! command -v cljstyle &> /dev/null
then
    echo "cljstyle could not be found. Please follow the installation instructions here https://github.com/greglook/cljstyle#installation"
    exit 2
fi

if !(cljstyle $1)
then
    echo
    echo "Error: new cljstyle errors found. Please fix them and retry the commit."
    exit 1
fi